### ISSUE TITLE
Recovered videos titled "Deleted Video"

### ISSUE THREAD

**Issue by brunogarciavaz** [ninsky/recovermyvideotracker#17]
I've never got this tool to work with my playlists, whenever a video is deleted, the recovered video is just "Deleted Video" with no extra information whatsoever
![image](https://user-images.githubusercontent.com/18823252/83662564-0b3a3000-a59e-11ea-952b-f31bd4938ef6.png)

Is this tool still working?

**Comment by ninsky** [comment]
Hello Bruno

Thanks for this bug report. I've checked RecoverMy.Video's database and can confirm, that there are some videos, which have "Deleted video" as a title instead of the correct title of the video.

I think this bug occurs due to an inconsistency regarding the handling of deleted videos in YouTube's API. Users experienced a similar issue with private videos which I could fix. I think that I should be able to fix this too.

Will give this bugfix my highest priority. I'll let you know as soon as it's fixed.

BR
Nino

**Comment by Shadetail** [comment]
I'm also having this issue last few months and maybe it's just bad luck but it's as if it's getting worse. Today I got an email about new deleted videos just to be greeted by this:

![chrome_2020-08-03_08-39-04](https://user-images.githubusercontent.com/11357447/89153269-d9752380-d564-11ea-9b5f-0b14d62a6315.png)

links to broken videos in the screenshot:
https://www.youtube.com/watch?v=HA5CIJxoFFE
https://www.youtube.com/watch?v=vXPopExzmV8
https://www.youtube.com/watch?v=vXPopExzmV8
https://www.youtube.com/watch?v=HA5CIJxoFFE

**Comment by ninsky** [comment]
Hello Shadetail, 

yes, it's getting worse. I've already fixed this issue on my development environment but have to implement another feature first, as this update will need a database flush. Hope to roll it out within the next 3-4 weeks.

BR
Nino

**Comment by brunogarciavaz** [comment]
It seems to be working alright lately. Thanks!

Just a small suggestion, whenever I get an email and return to the website, I'm greeted with a page that makes me think I need to register again and accept the privacy policy (instead of logging in). This made me very confused the first time. You could instead make the email link redirect to a Login Page and add a Login link on the main page :smile:

**Comment by ninsky** [comment]
**>It seems to be working alright lately. Thanks!**
So you have been lucky to be not affected that much. The YouTube API is not consistent in some parts. Maybe there's some kind of regional depedency. Anyway, still working on a fix which will handle all cases.

**>Just a small suggestion**
Yes, you're right. Also working on a new kind of user login which will fix this issue soon.

**Comment by JaredF** [comment]
Unfortunately I’m still seeing this issue. The last two recovered videos in my account only show as “Deleted Video”

**Comment by ninsky** [comment]
Yes, I've still working on a release which will contain a bugfix for this issue. Will be fixed soon and I'm gonna notify all users as soon as I will push this to production. It's already working on my development environment.

**Comment by ninsky** [comment]
This should be fixed! Please let me know if you still encounter this bug. I'm closing this ticket by now.

BR
Nino
